print(10)
print("welcome")
print("hello")
print("hi")
print("atharv")
print("ronaldo")
print("ronaldo is the goat")
print("india won the world cup")
print(22)
print(2.5)
print(3.5)
print(10,"welcome","hello","hi","atharv","ronaldo","ronaldo is the goat","india won the world cup",22,2.5,3.5)
print(10,"\nwelcome","\nhello","\nhi","\natharv","\nronaldo","\nronaldo is the goat","\nindia won the world cup\n",22,"\n",2.5,"\n", F78GAZEWS]zcx3.5)